
using HelpingHands_Client.Service.IService;
using HelpingHands_Common;
using HelpingHands_Models;
using HelpingHands_Models.API;

namespace HelpingHands_Client.Service{    public class AmenityService : BaseService, IAmenityService    {        private readonly IHttpClientFactory _clientFactory;        private string categoryUrl;        public AmenityService(IHttpClientFactory clientFactory, IConfiguration configuration) : base(clientFactory)        {            _clientFactory = clientFactory;            categoryUrl = configuration.GetValue<string>("ServiceUrls:HelpingHandAPI");        }        public Task<T> CreateAsync<T>(AmenityCreateDTO dto)        {            return SendAsync<T>(new APIRequest()            {                ApiType = SD.ApiType.POST,                Data = dto,                Url = categoryUrl + "/api/v1/AmenityAPI/CreateAmenity",                //Token = token            });        }        public Task<T> DeleteAsync<T>(int id)        {            return SendAsync<T>(new APIRequest()            {                ApiType = SD.ApiType.DELETE,                Url = categoryUrl + "/api/v1/AmenityAPI/DeleteAmenity/" + id,                //Token = token            });        }        public Task<T> GetAllAsync<T>()        {            return SendAsync<T>(new APIRequest()            {                ApiType = SD.ApiType.GET,                Url = categoryUrl + "/api/v1/AmenityAPI/GetAmenitys",                //Token = token            });        }

        public Task<T> AmenityByPagination<T>(string term, string orderBy, int currentPage)        {
            //string apiUrl = $"{carUrl}/api/v1/StateAPI/GetStatesData/{Id}/{search}/{pageSize}/{pageNumber}";
            string apiUrl = $"{categoryUrl}/api/v1/AmenityAPI/AmenityByPagination?term={term}&orderBy={orderBy}&currentPage={currentPage}";            return SendAsync<T>(new APIRequest()            {                ApiType = SD.ApiType.GET,                Url = apiUrl,                //Token = token            });        }        public Task<T> GetAsync<T>(int id)        {            return SendAsync<T>(new APIRequest()            {                ApiType = SD.ApiType.GET,                Url = categoryUrl + "/api/v1/AmenityAPI/GetAmenity/" + id,                //Token = token            });        }        public Task<T> UpdateAsync<T>(AmenityUpdateDTO dto)        {            return SendAsync<T>(new APIRequest()            {                ApiType = SD.ApiType.PUT,                Data = dto,                Url = categoryUrl + "/api/v1/AmenityAPI/UpdateAmenity/" + dto.Id,                //Token = token            });        }    }}